<?php

namespace App\Http\Controllers\V1;

use App\Domain\Task\TaskService;
use App\Domain\Transfer\TransferService;
use App\ErrCode;
use App\Foundation\DTO\TaskDTO;
use App\Http\Service\DownloadService;
use WecarSwoole\Container;
use WecarSwoole\Http\Controller;

class Download extends Controller
{
    use ParamUtil;

    protected function validateRules(): array
    {
        return [
            'asyncGetData' => [
                'task_id' => ['required', 'lengthMax' => 100],
            ],
            'getDownloadUrl' => [
                'task_id' => ['required', 'lengthMax' => 100],
            ],
            'getData' => [
                'ticket' => ['required', 'lengthMax' => 100],
            ],
            'syncGetData' => [
                'source_url' => ['optional', 'url', 'lengthMin' => 2, 'lengthMax' => 5000],
                'name' => ['required', 'lengthMin' => 2, 'lengthMax' => 60],
                'project_id' => ['required', 'lengthMax' => 40],
                'file_name' => ['lengthMax' => 120],
                'type' => ['inArray' => [null, 'csv', 'excel']],
                'callback' => ['lengthMax' => 300],
                'operator_id' => ['lengthMax' => 120],
                'template' => ['required', 'lengthMax' => 100000],
                'title' => ['lengthMax' => 200],
                'summary' => ['lengthMax' => 8000],
                'interval' => ['optional', 'integer', 'min' => 100, 'max' => 3000],
                'rowoffset' => ['optional', 'integer', 'min' => 0,],
            ],
            'syncGetDataMultiple' => [
                'source_data' => ['optional'],
                'source' => ['optional'],
                'name' => ['required', 'lengthMin' => 2, 'lengthMax' => 60],
                'project_id' => ['required', 'lengthMax' => 40],
                'file_name' => ['lengthMax' => 120],
                'type' => ['inArray' => [null, 'excel']],
                'callback' => ['lengthMax' => 300],
                'operator_id' => ['lengthMax' => 120],
                'merchant_type' => ['required', 'integer'],
                'merchant_id' => ['required', 'integer'],
                'interval' => ['optional', 'integer', 'min' => 100, 'max' => 3000],
                'template' => ['required', 'lengthMax' => 100000],
                'rowoffset' => ['optional', 'integer', 'min' => 0,],
            ],
        ];
    }

    /**
     * Fetch data
     * Download data after backend authentication
     * Note: The caller should handle large file downloads carefully. Using functions like file_get_contents
     * to load all data into memory at once may cause memory overflow. In such cases, use curl's
     * CURLOPT_WRITEFUNCTION to stream data to a local file instead.
     */
    public function asyncGetData()
    {
        Container::get(DownloadService::class)->download($this->params('task_id'), $this->response());
    }

    /**
     * Get temporary download URL
     */
    public function getDownloadUrl()
    {
        $task = Container::get(TaskService::class)->getTask($this->params('task_id'));
        if (!$task) {
            return $this->return([], ErrCode::TASK_NOT_EXISTS, "Task {$this->params('task_id')} does not exist");
        }

        $this->return(['url' => Container::get(TransferService::class)->buildDownloadUrlNew($task)]);
    }

    /**
     * Frontend downloads data via temporary download URL
     * No authentication required. The URL is generated by getDownloadUrl.
     * @deprecated This method is deprecated. Async downloads now go directly through OSS temporary URLs, no longer via the download center.
     */
    public function getData()
    {
        Container::get(DownloadService::class)->downloadWithTicket($this->params('ticket'), $this->response());
    }

    /**
     * Synchronous data download
     * Combines task delivery and data retrieval into one operation, used for small-batch data downloads.
     */
    public function syncGetData()
    {
        Container::get(DownloadService::class)
        ->syncDownload(new TaskDTO(self::dealParams($this->params())), $this->response());
    }

    /**
     * Synchronous multi-table data download
     */
    public function syncGetDataMultiple()
    {
        $params = self::dealParams(array_merge(['multi_type' => 'page'], $this->params(), ['type' => 'excel']));
        Container::get(DownloadService::class)
        ->syncDownload(new TaskDTO($params), $this->response());
    }
}
